np.zeros
np.ones (mesmo principio do zero)
np.arange
np.random.randint

In [4]:
import numpy as np

lista_1 = np.array([1,2,3,4,5])


In [5]:
lista_1 = np.array([1,2,3,4,5],dtype = 'float32')
print(lista_1)

[1. 2. 3. 4. 5.]


In [7]:
vetor_zeros = np.zeros(5)
vetor_zeros

matrix_zeros = np.zeros((2,5))
matrix_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
#criando um array de numeros pares
pares = np.arange(0,201,2)
pares 

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [11]:
#criando uma matrix 3,2 com valores randomicos

np.random.rand(3,2)

array([[0.09337039, 0.70989138],
       [0.98268919, 0.31883544],
       [0.87939252, 0.16389943]])

In [17]:
array_1 = np.random.rand(1,3)
100*array_1

array([[40.80335253, 20.62377086, 59.74137572]])